name: Run d2d pipeline
'on':
  workflow_dispatch: null
  push:
    tags:
      - v*.*.*
jobs:
  build-and-publish-to-pypi:
    name: Build and publish library to PyPI
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install pypa/build
        run: python -m pip install build --user
      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/
      - name: Upload built archives
        uses: actions/upload-artifact@v4
        with:
          name: build_archives
          path: dist/*.whl

  run-d2d-pipeline:
    name: Run d2d pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Download build archive
        uses: actions/download-artifact@v4
        with:
          name: build_archives
          path: scancode-inputs/
      - name: Prepare inputs for d2d
        shell: bash
        run: |
          git archive --format=tar.gz -o scancode-inputs/from.tar.gz HEAD
          cp scancode-inputs/*.whl scancode-inputs/to_$(basename scancode-inputs/*.whl)
      - name: Run d2d pipeline
        uses: aboutcode-org/scancode-action@beta
        with:
          pipelines: map_deploy_to_develop
