name: Run d2d pipeline
'on':
  workflow_dispatch: null
  push:
    tags:
      - v*.*.*
jobs:
  build-wheel:
    name: Build wheel for package
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install pypa/build
        run: python -m pip install build --user
      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/
      - name: Upload built archives
        uses: actions/upload-artifact@v4
        with:
          name: build_archives
          path: dist/*.whl
    

  run-d2d-pipeline:
    needs: build-wheel
    uses: aboutcode-org/scancode-action/.github/workflows/map-deploy-to-develop-template.yml@d2d-template
    with:
      artifact-name: build_archives
      steps: ""
